### ISSUE TITLE
Workflow instances that are in error should have their end date set

### ISSUE THREAD

**Issue by krisv** [apache/incubator-kie-kogito-runtimes#3372] opened 2024-01-25 13:59 UTC
### Describe the bug

In some UIs, showing running process instances, the end date of shown or used to calculate duration.  For process instances that are in error state, it seems the process instance end date is not set in the data index.  Since process instances in error state cannot be recovered, my suggestion is that the end date is set for these instances as well (similar to completed and aborted).

**Comment by fjtirado** [comment] 2024-01-25 15:13
@krisv The issue is not that the end date is not set.  Thats a side effect of current runtimes behaviour. Currently a process in error state is still kept active (in memory or in db) by runtimes. Should we change that behaviour and complete a process instance that is on error? If so, error state will behave like aborted or completed states, unlike now, which behaves as active state.

**Comment by fjtirado** [comment] 2024-01-26 16:16
Closing together with the PR. In error processes are process that are still active so user might retry changing variables. So "error" state should be understood  "as active with previous attempt failed because of an recoverable error"

**Closed** 2024-02-06 12:13 UTC
